/**
 * Webpack configuration for Grafana panel plugin.
 * Generated for sid2-grafana-topology.
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY.
 * Extend the configuration from the project root instead.
 * @see https://grafana.com/developers/plugin-tools/how-to-guides/extend-configurations
 */

import CopyWebpackPlugin from 'copy-webpack-plugin';
import ESLintPlugin from 'eslint-webpack-plugin';
import ForkTsCheckerWebpackPlugin from 'fork-ts-checker-webpack-plugin';
// @ts-ignore - no type declarations available
import LiveReloadPlugin from 'webpack-livereload-plugin';
import path from 'path';
// @ts-ignore - no type declarations available
import ReplaceInFileWebpackPlugin from 'replace-in-file-webpack-plugin';
import { Configuration } from 'webpack';
import { getEntries, getPluginJson, hasReadme, isWSL, getPackageJson } from './utils';
import { DIST_DIR, SOURCE_DIR } from './constants';

export type Env = Record<string, unknown>;

const config = async (env: Env): Promise<Configuration> => {
  const pluginJson = getPluginJson();
  const packageJson = getPackageJson();
  const isProduction = env.production === true;

  const baseConfig: Configuration = {
    cache: {
      type: 'filesystem',
      buildDependencies: {
        config: [__filename],
      },
    },

    context: process.cwd(),

    devtool: isProduction ? 'source-map' : 'eval-source-map',

    entry: getEntries(),

    externals: [
      'lodash',
      'jquery',
      'moment',
      'slate',
      'emotion',
      '@emotion/react',
      '@emotion/css',
      'prismjs',
      'slate-plain-serializer',
      '@grafana/slate-react',
      'react',
      'react-dom',
      'react-redux',
      'redux',
      'rxjs',
      'react-router',
      'react-router-dom',
      'd3',
      'angular',
      '@grafana/ui',
      '@grafana/runtime',
      '@grafana/data',

      /**
       * Mark the @grafana/plugin-ui as external so that it uses the same
       * runtime copy of react, @grafana/data, @grafana/ui, etc.
       */

      // The below are imported by @grafana/ui in some Grafana versions
      function (data: { request?: string }, callback: (err?: null | Error, result?: string) => void) {
        const request = data.request || '';
        const prefix = '@grafana/';
        if (request.indexOf(prefix) === 0) {
          return callback(null, request);
        }
        callback();
      },
    ],

    mode: isProduction ? 'production' : 'development',

    module: {
      rules: [
        {
          exclude: /(node_modules)/,
          test: /\.[tj]sx?$/,
          use: {
            loader: 'swc-loader',
            options: {
              jsc: {
                baseUrl: '.',
                target: 'es2020',
                loose: false,
                parser: {
                  syntax: 'typescript',
                  tsx: true,
                  decorators: false,
                  dynamicImport: true,
                },
              },
            },
          },
        },
        {
          test: /\.css$/,
          use: ['style-loader', 'css-loader'],
        },
        {
          test: /\.s[ac]ss$/,
          use: ['style-loader', 'css-loader', 'sass-loader'],
        },
        {
          test: /\.(png|jpe?g|gif|webp)$/,
          type: 'asset/resource',
          generator: {
            filename: isProduction ? 'img/[hash][ext]' : 'img/[name][ext]',
            publicPath: `public/plugins/${pluginJson.id}/`,
            outputPath: './',
          },
        },
        {
          test: /\.svg$/,
          type: 'asset/resource',
          generator: {
            filename: isProduction ? 'img/[hash][ext]' : 'img/[name][ext]',
            publicPath: `public/plugins/${pluginJson.id}/`,
            outputPath: './',
          },
        },
        {
          test: /\.(woff|woff2|eot|ttf|otf)(\?v=\d+\.\d+\.\d+)?$/,
          type: 'asset/resource',
          generator: {
            filename: isProduction ? 'fonts/[hash][ext]' : 'fonts/[name][ext]',
            publicPath: `public/plugins/${pluginJson.id}/`,
            outputPath: './',
          },
        },
      ],
    },

    output: {
      clean: {
        keep: new RegExp(`(.*?_(amd64|arm(64)?)(.exe)?|gpx_.*)`),
      },
      filename: '[name].js',
      library: {
        type: 'amd',
      },
      path: DIST_DIR,
      publicPath: `public/plugins/${pluginJson.id}/`,
      uniqueName: pluginJson.id,
    },

    plugins: [
      new CopyWebpackPlugin({
        patterns: [
          { from: path.resolve(SOURCE_DIR, 'plugin.json'), to: '.', noErrorOnMissing: true },
          { from: path.resolve(process.cwd(), 'README.md'), to: '.', noErrorOnMissing: true },
          { from: path.resolve(process.cwd(), 'CHANGELOG.md'), to: '.', noErrorOnMissing: true },
          { from: path.resolve(process.cwd(), 'LICENSE'), to: '.', noErrorOnMissing: true },
          { from: '**/*.json', to: '.', context: path.resolve(SOURCE_DIR) },
          { from: '**/*.svg', to: '.', context: path.resolve(SOURCE_DIR), noErrorOnMissing: true },
          { from: '**/*.png', to: '.', context: path.resolve(SOURCE_DIR), noErrorOnMissing: true },
          { from: 'img/**/*', to: '.', context: path.resolve(SOURCE_DIR), noErrorOnMissing: true },
        ],
      }),
      new ReplaceInFileWebpackPlugin([
        {
          dir: DIST_DIR,
          files: ['plugin.json'],
          rules: [
            {
              search: '%VERSION%',
              replace: packageJson.version,
            },
            {
              search: '%TODAY%',
              replace: new Date().toISOString().substring(0, 10),
            },
          ],
        },
      ]),
      ...(isProduction
        ? []
        : [
            new LiveReloadPlugin(),
            new ForkTsCheckerWebpackPlugin({
              async: Boolean(env.development),
              issue: {
                include: [{ file: '**/*.{ts,tsx}' }],
              },
              typescript: {
                configFile: path.resolve(process.cwd(), 'tsconfig.json'),
              },
            }),
            new ESLintPlugin({
              extensions: ['ts', 'tsx'],
              lintDirtyModulesOnly: true,
            }),
          ]),
    ],

    resolve: {
      extensions: ['.js', '.jsx', '.ts', '.tsx'],
      unsafeCache: true,
    },

    ...(isProduction
      ? {
          optimization: {
            minimize: true,
          },
        }
      : {}),

    watchOptions: {
      ignored: ['**/node_modules'],
      ...(isWSL() ? { poll: 1000 } : {}),
    },
  };

  return baseConfig;
};

export default config;
