/**
 * Jest configuration for Grafana plugin.
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY.
 */
const path = require('path');
const { lstatSync, readdirSync } = require('fs');

// Use SWC for faster Jest transforms
const swcJestConfig = {
  jsc: {
    baseUrl: '.',
    target: 'es2021',
    loose: false,
    parser: {
      syntax: 'typescript',
      tsx: true,
      decorators: false,
      dynamicImport: true,
    },
  },
};

module.exports = {
  moduleNameMapper: {
    '\\.(css|scss|sass)$': 'identity-obj-proxy',
    '\\.(svg|png|jpg|jpeg|gif)$': '<rootDir>/.config/jest/mocks/react-inlinesvg.tsx',
  },
  testEnvironment: 'jest-environment-jsdom',
  testMatch: [
    '<rootDir>/src/**/*.{spec,test}.{js,jsx,ts,tsx}',
  ],
  transform: {
    '^.+\\.(t|j)sx?$': ['@swc/jest', swcJestConfig],
  },
  transformIgnorePatterns: [
    'node_modules/(?!(@grafana|d3|d3-[^/]+|internmap|robust-predicates|delaunator)/)',
  ],
  setupFilesAfterEnv: ['<rootDir>/jest-setup.js'],
};
